// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Book struct {
	ID              string
	Title           string
	Isbn            int64
	PublicationDate sql.NullString
	NumberOfPages   sql.NullInt64
}
